### PR TITLE
Disabling special perception on pf1e

### PR DESCRIPTION
**Pull request by ManaHime**
The special perception doesn't use the correct info on pf1e, so disabling while I figure out how to make it better.

### CODE REVIEW

**Comment by ManaHime** [comment]
I'm really sorry, I didn't realize that it didn't work before. So this is just a very small hotfix since using perception will not actually produce the expected result for pf1e players

**Comment by akrigline** [comment]
Sure thing, I'll get this out today, thanks for taking this system support on!

**Comment by ManaHime** [comment]
I am not sure if this just randomly added my last commit but after talking in #pf1e on discord we realised that initiatives roles weren't being added to the combat tracker. 
We realized that the roller for it was specifically looking for dnd5e
So this line:
if(game.system.id == "dnd5e") {
Could be changed like this and then it would work for everyone who sets this.data.initiative to true:
if(this.data.initiative) {
I am not sure if this will affect 5e in some way as I am not knowledgeable about the system. But I think that it would help every system that didn't have this ability before.

**Comment by akrigline** [comment]
Ahh, I did wonder if that was more generic. I'm not opposed to making that change.

**Comment by ManaHime** [comment]
I'm sorry if this is a little chaotic, I don't really know how to use github properly, but this should be all for now.
There are a few things that I would like to do in the future like setting the pf1 perception skill as the custom perception thing (since this would allow to have it separate since it's used so much)
But this can wait for when I have more time.
If there is any issue, please let me know ^^

**Pull request merged**
