### PR TITLE
skills sorting based off localized skill name

### PR DESCRIPTION
**Pull request by santalucial**

### CODE REVIEW

**Review by akrigline — CHANGES_REQUESTED** [review]
This seems pretty dramatically overengineered. Can't the same be done with a simple `.sort( (a,b) => a.localeCompare(b)`?

**Comment by akrigline** [comment]
Ok I understand why this isn't quite as simple as I thought. The localization doesn't happen until the handlebars layer normally, so a localeCompare only kind of helps. It would need to be coupled with `game.i18n.localize`.

**Comment by akrigline** [comment]
Closing in favor of #51. Thanks for your contribution though!

**Comment by santalucial** [comment]
The issue is still present in 1.8 despite #51 
image

**Pull request closed without merging**
