### PR TITLE
System Support: Tormenta20

### PR DESCRIPTION
**Pull request by mclemente**
Hello, I'm a dev of the [Tormenta20 system](https://gitlab.com/vizael/Tormenta20) (a brazilian d20 system) and this PR adds support to it.
The system's saving throws are skills too, so I've made changes to the template to make it so it doesn't show an empty Saving Throw fieldset. The change only affects systems that return an empty `LMRTFY.saves`, so it doesn't affect the other systems. I've tested this change on dnd5e.
I've also improved some of the Portuguese translation and added the new lines from 1.6.

### CODE REVIEW

**Comment by akrigline** [comment]
Wonderful! Thanks for your contribution! I'll see about getting this merged in this week.

**Comment by mclemente** [comment]
I've converted this to a draft since we haven't released the update for our system yet (we've refactored our roll system) and I'm fixing some issues on our side.

**Comment by vtt-lair** [comment]
@mclemente any progress on this? There has been quite a few changes on the system since your initial PR. Otherwise I would like to close the PR for now, as you'll have to pull the latest into your branch in any case.

**Comment by mclemente** [comment]
Unfortunately, we haven't made many changes to how rolls work on the system and we're still updating it to FVTT 0.8.

**Pull request closed without merging**
